server:
  port: 8000
spring:
  application:
    name: microservice-provider-user    # 项目名称尽量用小写
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: h2                        # 指定数据源类型
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
    data: classpath:data.sql            # 指定h2数据库的insert脚本
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true

   #心跳时间 和 等待心跳时间 - 必须有
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 30
    preferIpAddress: true
  client:
    healthcheck.enabled: true
    # 请求超时时间设置 - 必须有
hystrix:
  command:
    default:
     execution:
       isolation:
        thread:
          timeoutInMilliseconds: 30000
  threadpool:
    default:
      coreSize: 50
      maxQueueSize: 100

#   #心跳时间 和 等待心跳时间 - 必须有
#   eureka.instance.leaseRenewalIntervalInSeconds = 5
#   eureka.instance.leaseExpirationDurationInSeconds = 30
#   eureka.client.healthcheck.enabled = true
#   eureka.instance.preferIpAddress=true
#   # 请求超时时间设置 - 必须有
#   hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=30000
#   hystrix.threadpool.default.coreSize=50
#   hystrix.threadpool.default.maxQueueSize=100